defaults: &defaults
  docker:
    - image: gcr.io/planet-4-151612/p4-builder:latest
  working_directory:  /home/circleci/

version: 2

jobs:
  build-develop:
    <<: *defaults
    environment:
      APP_ENVIRONMENT: development
      APP_HOSTNAME: k8s.p4.greenpeace.org
      APP_HOSTPATH: eu-unit
      CLOUDSQL_INSTANCE: p4-develop-k8s
      CONTAINER_PREFIX: planet4-eu-unit
      GOOGLE_PROJECT_ID: planet-4-151612
      HELM_NAMESPACE: develop
      TYPE: "Container Build - planet4-eu-unit-x"
      WP_DB_NAME: eu-unit_wordpress_develop
      WP_STATELESS_BUCKET: planet4-eu-unit-stateless-develop
      WP_TITLE: Greenpeace EU Unit Development
    steps:
      - setup_remote_docker

      - run:
          name: Configure
          command: |
            ${HOME}/scripts/activate-gcloud-account.sh
            mkdir -p /tmp/workspace/var
            echo "${CIRCLE_BUILD_NUM}" > /tmp/workspace/var/circle-build-num

      - run:
          name: Build
          working_directory: /home/circleci
          command: |
            if ! make
            then
              ${HOME}/scripts/notify-job-failure.sh
              exit 1
            fi

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - var

  # test:
  #   <<: *defaults
  #   steps:
  #     - run:
  #         name: Placeholder
  #         command: |
  #           echo "Branch: ${CIRCLE_BRANCH}"
  #           echo "Build:  ${CIRCLE_BUILD_NUM}"
  #           echo "Tag:    ${CIRCLE_TAG}"
  #           echo "No tests implemented yet"

  deploy-develop:
    <<: *defaults
    environment:
      APP_ENVIRONMENT: development
      APP_HOSTNAME: k8s.p4.greenpeace.org
      APP_HOSTPATH: eu-unit
      CLOUDSQL_INSTANCE: p4-develop-k8s
      CONTAINER_PREFIX: planet4-eu-unit
      GOOGLE_PROJECT_ID: planet-4-151612
      HELM_NAMESPACE: develop
      WP_DB_NAME: eu-unit_wordpress_develop
      WP_STATELESS_BUCKET: planet4-eu-unit-stateless-develop
      WP_TITLE: Greenpeace EU Unit Development
    steps:
      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: Configure
          command: |
            ${HOME}/scripts/activate-gcloud-account.sh

      - run:
          name: Deploy new containers
          environment:
            NEWRELIC_APPNAME: P4 EU Unit Development
          command: |
            export BUILD_TAG=build-$(cat /tmp/workspace/var/circle-build-num)
            make -j2 deploy

  build-release:
    <<: *defaults
    environment:
      APP_ENVIRONMENT: staging
      APP_HOSTNAME: release.k8s.p4.greenpeace.org
      APP_HOSTPATH: eu-unit
      CLOUDSQL_INSTANCE: planet4-prod
      CONTAINER_PREFIX: planet4-eu-unit
      GCLOUD_CLUSTER: planet4-production
      GOOGLE_PROJECT_ID: planet4-production
      HELM_NAMESPACE: eu-unit
      HELM_RELEASE: planet4-eu-unit-release
      TYPE: "Container Build - planet4-eu-unit-x"
      WP_DB_NAME: eu-unit_wordpress_release
      WP_STATELESS_BUCKET: planet4-eu-unit-stateless-release
      WP_TITLE: Greenpeace EU Unit Release Candidate
    steps:
      - setup_remote_docker

      - run:
          name: Configure
          command: |
            ${HOME}/scripts/activate-gcloud-account.sh
            mkdir -p /tmp/workspace/var
            echo "${CIRCLE_BUILD_NUM}" > /tmp/workspace/var/circle-build-num

      - run:
          name: Build
          working_directory: /home/circleci
          command: |
            if ! make
            then
              ${HOME}/scripts/notify-job-failure.sh
              exit 1
            fi

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - var

  # test-release:
  #   <<: *defaults
  #   steps:
  #     - run:
  #         name: Placeholder
  #         command: |
  #           echo "Branch: ${CIRCLE_BRANCH}"
  #           echo "Build:  ${CIRCLE_BUILD_NUM}"
  #           echo "Tag:    ${CIRCLE_TAG}"
  #           echo "No tests implemented yet"

  deploy-release:
    <<: *defaults
    environment:
      APP_ENVIRONMENT: staging
      APP_HOSTNAME: release.k8s.p4.greenpeace.org
      APP_HOSTPATH: eu-unit
      CLOUDSQL_INSTANCE: planet4-prod
      CONTAINER_PREFIX: planet4-eu-unit
      GCLOUD_CLUSTER: planet4-production
      GOOGLE_PROJECT_ID: planet4-production
      HELM_NAMESPACE: eu-unit
      HELM_RELEASE: planet4-eu-unit-release
      WP_DB_NAME: eu-unit_wordpress_release
      WP_STATELESS_BUCKET: planet4-eu-unit-stateless-release
      WP_TITLE: Greenpeace EU Unit Release Candidate
    steps:
      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: Configure
          command: |
            ${HOME}/scripts/activate-gcloud-account.sh

      - run:
          name: Deploy new containers
          environment:
            NEWRELIC_APPNAME: P4 EU Unit Release
          command: |
            export BUILD_TAG=build-$(cat /tmp/workspace/var/circle-build-num)
            make -j2 deploy

  build-tag:
    <<: *defaults
    environment:
      APP_HOSTNAME: www.greenpeace.org
      APP_HOSTPATH: eu-unit
      CLOUDSQL_INSTANCE: planet4-prod
      CONTAINER_PREFIX: planet4-eu-unit
      GCLOUD_CLUSTER: planet4-production
      GOOGLE_PROJECT_ID: planet4-production
      HELM_NAMESPACE: eu-unit
      HELM_RELEASE: planet4-eu-unit-master
      MIN_REPLICA_COUNT: 2
      TYPE: "Tagged Container Build - planet4-eu-unit-x"
      WP_DB_NAME: eu-unit_wordpress_master
      WP_STATELESS_BUCKET: planet4-eu-unit-stateless
      WP_TITLE: Greenpeace EU Unit
    steps:
      - setup_remote_docker

      - run:
          name: Configure
          command: |
            ${HOME}/scripts/activate-gcloud-account.sh
            mkdir -p /tmp/workspace/var
            echo "${CIRCLE_BUILD_NUM}" > /tmp/workspace/var/circle-build-num

      - run:
          name: Build
          working_directory: /home/circleci
          command: |
            if ! make
            then
              ${HOME}/scripts/notify-job-failure.sh
              exit 1
            fi

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - var

  # test-tag:
  #   <<: *defaults
  #   steps:
  #     - run:
  #         name: Placeholder
  #         command: |
  #           echo "Branch: ${CIRCLE_BRANCH}"
  #           echo "Build:  ${CIRCLE_BUILD_NUM}"
  #           echo "Tag:    ${CIRCLE_TAG}"
  #           echo "No tests implemented yet"

  deploy-tag:
    <<: *defaults
    environment:
      APP_HOSTNAME: www.greenpeace.org
      APP_HOSTPATH: eu-unit
      CLOUDSQL_INSTANCE: planet4-prod
      CONTAINER_PREFIX: planet4-eu-unit
      GCLOUD_CLUSTER: planet4-production
      GOOGLE_PROJECT_ID: planet4-production
      HELM_NAMESPACE: eu-unit
      HELM_RELEASE: planet4-eu-unit-master
      WP_DB_NAME: eu-unit_wordpress_master
      WP_STATELESS_BUCKET: planet4-eu-unit-stateless
      WP_TITLE: Greenpeace EU Unit
    steps:
      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: Configure
          command: |
            ${HOME}/scripts/activate-gcloud-account.sh

      - run:
          name: Deploy new containers
          environment:
            NEWRELIC_APPNAME: P4 EU Unit Production
          command: |
            make -j2 deploy

workflows:
  version: 2
  develop:
    jobs:
    - build-develop:
        context: org-global
        filters:
          branches:
            only: develop
          tags:
            ignore: /^v.*/

    - deploy-develop:
        context: org-global
        requires:
          - build-develop
        filters:
          branches:
            only: develop

  release:
    jobs:
    - build-release:
        context: org-global
        filters:
          branches:
            only: /^release.*/
          tags:
            ignore: /^v.*/

    - deploy-release:
        context: org-global
        requires:
          - build-release
        filters:
          branches:
            only: /^release.*/
          tags:
            ignore: /^v.*/

  tag:
    jobs:
      - build-tag:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - hold-tag:
          type: approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - build-tag

      - deploy-tag:
          context: org-global
          requires:
            - hold-tag
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
